# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce7b7280bf41c424b2bfb417d947727f40b20fdee4142e828d984da10112ad71759e1c84a8ff74d48a4cb8e3ee8e0e5c6c5ce92b5f93550bc52db6e2944c9e9e

test:
  secret_key_base: 7a2e7d80a200ef3e9daaf8c017bd2ed6de9a963b83d140601ad04125a34f0c8f92fafac60ed70fa2c5ef3c50b427d1a40c0fe04dd85799227ec924380d25d363

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
